# Generated by Django 5.1.3 on 2024-11-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Employee_Id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
